#!/usr/bin/env python3
"""Regenerates Resources/<lang>.lproj/Localizable.strings from the Swift sources and scripts/translations/<lang>.py.

Each translation file defines `T = {english_source_string: translation}`. Keys are the English strings exactly as written
in Swift (escapes included). Run: python3 scripts/gen_strings.py — it reports missing translations and refuses format
strings whose %@ / %d placeholders differ from the English ones (a mismatch would crash String(format:)).
"""
import glob
import importlib.util
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRANSLATIONS = os.path.join(ROOT, 'scripts', 'translations')


def extract():
    keys = set()
    for f in glob.glob(os.path.join(ROOT, 'Sources/Brushwood/**/*.swift'), recursive=True):
        for m in re.finditer(r'\bLF?\("((?:[^"\\]|\\.)*)"', open(f).read()):
            keys.add(m.group(1))
    core_like = glob.glob(os.path.join(ROOT, 'Sources/BrushwoodCore/**/*.swift'), recursive=True)
    core_like += [os.path.join(ROOT, 'Sources/Brushwood/App/EffectsController.swift')]
    for f in core_like:
        s = open(f).read()
        pats = [r'override var name: String \{ "([^"]+)" \}', r'label: "([^"]+)"', r'case \.\w+: return "([^"]+)"',
                r'requiresSelectionHint: String\? \{\s*"([^"]+)"', r'case \w+ = "([A-Z][a-z]+)"']
        for p in pats:
            keys.update(re.findall(p, s))
        for m in re.finditer(r'options: \[([^\]]+)\]', s):
            keys.update(re.findall(r'"([^"]+)"', m.group(1)))
        for m in re.finditer(r'\[("Clamp".*?)\]', s):
            keys.update(re.findall(r'"([^"]+)"', m.group(1)))
    return sorted(k for k in keys if not k.startswith(('svg:', 'brushwood:', 'sym.', 'app.brushwood')))


PLACEHOLDER = re.compile(r'%(?:\d+\$)?[-+ #0]*\d*(?:\.\d+)?(?:l|ll|h)?[@dDiuUxXoOfeEgGcCsSp]')


def placeholders(s):
    return [re.sub(r'\d+\$', '', p) for p in PLACEHOLDER.findall(s)]


def load(path):
    spec = importlib.util.spec_from_file_location(os.path.basename(path), path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.T


def main():
    keys = extract()
    ok = True
    for path in sorted(glob.glob(os.path.join(TRANSLATIONS, '*.py'))):
        lang = os.path.splitext(os.path.basename(path))[0]
        table = load(path)
        missing = [k for k in keys if k not in table]
        out = [f'/* Generated by scripts/gen_strings.py from scripts/translations/{lang}.py. */', '']
        for k in keys:
            v = table.get(k)
            if v is None:
                continue
            if placeholders(k) != placeholders(v):
                print(f'[{lang}] PLACEHOLDER MISMATCH: {k!r} -> {v!r}')
                ok = False
                continue
            v = v.replace('"', '\\"') if '\\"' not in v else v
            out.append(f'"{k}" = "{v}";')
        d = os.path.join(ROOT, 'Resources', f'{lang}.lproj')
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, 'Localizable.strings'), 'w', encoding='utf-8') as f:
            f.write('\n'.join(out) + '\n')
        print(f'{lang}: {len(keys) - len(missing)}/{len(keys)} translated')
        for k in missing:
            print(f'  [{lang}] MISSING: {k}')
    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
