#!/usr/bin/env python3
"""Regenerates Resources/<lang>.lproj/Localizable.strings from the Swift sources.

Usage: python3 scripts/gen_strings.py   (reports untranslated keys)
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
from fr_translations import FR  # noqa: E402


def extract():
    keys = set()
    for f in glob.glob(os.path.join(ROOT, 'Sources/Brushwood/**/*.swift'), recursive=True):
        for m in re.finditer(r'\bLF?\("((?:[^"\\]|\\.)*)"', open(f).read()):
            keys.add(m.group(1))
    for f in glob.glob(os.path.join(ROOT, 'Sources/BrushwoodCore/**/*.swift'), recursive=True):
        s = open(f).read()
        pats = [r'override var name: String \{ "([^"]+)" \}', r'label: "([^"]+)"', r'case \.\w+: return "([^"]+)"',
                r'requiresSelectionHint: String\? \{\s*"([^"]+)"', r'case \w+ = "([A-Z][a-z]+)"']
        for p in pats:
            keys.update(re.findall(p, s))
        for m in re.finditer(r'options: \[([^\]]+)\]', s):
            keys.update(re.findall(r'"([^"]+)"', m.group(1)))
        for m in re.finditer(r'\[("Clamp".*?)\]', s):
            keys.update(re.findall(r'"([^"]+)"', m.group(1)))
    return sorted(k for k in keys if not k.startswith(('svg:', 'brushwood:')))


def main():
    keys = extract()
    missing = [k for k in keys if k not in FR]
    out = ['/* Generated by scripts/gen_strings.py — edit scripts/fr_translations.py instead. */', '']
    for k in keys:
        v = FR.get(k)
        if v is None:
            continue
        v = v.replace('"', '\\"') if '\\"' not in v else v
        out.append(f'"{k}" = "{v}";')
    d = os.path.join(ROOT, 'Resources/fr.lproj')
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, 'Localizable.strings'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(out) + '\n')
    print(f'{len(keys)} keys, {len(keys) - len(missing)} translated')
    for k in missing:
        print('MISSING:', k)


if __name__ == '__main__':
    main()
